server:
  port: 8082
spring:
  mail:
    host: smtp.163.com
    protocol: smtp
    default-encoding: utf-8
    password: DXAGBZYWKVOJNVSM
    username: daoyu5313@163.com
    port: 25
  rabbitmq:
    port: 5672
    host: 172.25.112.91
    username: guest
    password: guest
